apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: common-case-image-git
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: test
      - stage: uat
      - stage: prod
  template:
    metadata:
      name: common-case-image-git-{{stage}}
      annotations:
        kargo.akuity.io/authorized-stage: common-case-image-git:{{stage}}
    spec:
      project: default
      source:
        repoURL: https://github.com/<github-username>/kargo-demo-gitops.git
        # Kargo will update targetRevision to move new commits from the
        # kustomize branch into each stage
        targetRevision: placeholder
        path: stages/{{stage}}
        kustomize:
          images:
          # Kargo will update this value to move new images into each stage
          - public.ecr.aws/nginx/nginx=public.ecr.aws/nginx/nginx:placeholder
      destination:
        server: https://kubernetes.default.svc
        namespace: common-case-image-git-{{stage}}
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
  ignoreApplicationDifferences:
  - jqPathExpressions:
    - .spec.source.targetRevision
    - .spec.source.kustomize.images
